project:
  type: website
  output-dir: docs

website:
  title: "Tan Nguyen"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - Research.qmd
      - Publication.qmd
      - CV.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



