project:
  type: website
  output-dir: docs

website:
  title: "Tan Nguyen"
  search: false
  navbar:
    left:
      - href: index.qmd
        text: Home
      - Research.qmd
      - Publication.qmd
      - CV.qmd
    tools:
      - icon: github
        href: https://github.com/nnguyengiatan
      - icon: linkedin
        href: www.linkedin.com/in/tannguyen2406

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



